export const CityDummyData =[
    
    { cityname: 'Mumbai'},
    { cityname: 'Delhi'},
    { cityname: 'Bengaluru'},
    { cityname: 'Ahmedabad'},
    { cityname: 'Hyderabad'},
    { cityname: 'Chennai'},
    { cityname: 'Kolkata'},
    { cityname: 'Pune'},
    { cityname: 'Jaipur'},
    { cityname: 'Surat'},
    { cityname: 'Lucknow'},
    { cityname: 'Kanpur'},
    { cityname: 'Nagpur'},
    { cityname: 'Patna'},
    { cityname: 'Indore'},
    { cityname: 'Thane'},
    { cityname: 'Bhopal'},
    { cityname: 'Visakhapatnam'},
    { cityname: 'Vadodara'},
    { cityname: 'Firozabad'},
    { cityname: 'Ludhiana'},
    { cityname: 'Rajkot'},
    { cityname: 'Agra'},
    { cityname: 'Siliguri'},
    { cityname: 'Nashik'},
    { cityname: 'Faridabad'},
    { cityname: 'Patiala'},
    { cityname: 'Meerut'},
    { cityname: 'Kalyan-Dombivali'},
    { cityname: 'Vasai-Virar'},
    { cityname: 'Varanasi'},
    { cityname: 'Srinagar'},
    { cityname: 'Dhanbad'},
    { cityname: 'Jodhpur'},
    { cityname: 'Amritsar'},
    { cityname: 'Raipur'},
    { cityname: 'Allahabad'},
    { cityname: 'Coimbatore'},
    { cityname: 'Jabalpur'},
    { cityname: 'Gwalior'},
    { cityname: 'Vijayawada'},
    { cityname: 'Madurai'},
    { cityname: 'Guwahati'},
    { cityname: 'Chandigarh'},
    { cityname: 'Hubli-Dharwad'},
    { cityname: 'Amroha'},
    { cityname: 'Moradabad'},
    { cityname: 'Gurgaon'},
    { cityname: 'Aligarh'},
    { cityname: 'Solapur'},    
     
        




]