export const StateData =[
    
    { statename: 'Andaman and Nicobar Islands'},
    { statename: 'Andhra Pradesh'},
    { statename: 'Arunachal Pradesh'},
    { statename: 'Assam'},
    { statename: 'Bihar'},
    { statename: 'Chandigarh'},
    { statename: 'Chhattisgarh'},
    { statename: 'Dadra and Nagar Haveli'},
    { statename: 'Daman and Diu'},
    { statename: 'Delhi'},
    { statename: 'Goa'},
    { statename: 'Gujarat'},
    { statename: 'Haryana'},
    { statename: 'Himachal Pradesh'},
    { statename: 'Jammu and Kashmir'},
    { statename: 'Jharkhand'},
    { statename: 'Karnataka'},
    { statename: 'Kerala'},
    { statename: 'Ladakh'},
    { statename: 'Lakshadweep'},
    { statename: 'Madhya Pradesh'},
    { statename: 'Maharashtra'},

    { statename: 'Manipur'},
    { statename: 'Meghalaya'},
    { statename: 'Mizoram'},
    { statename: 'Nagaland'},
    { statename: 'Odisha'},
    { statename: 'Puducherry'},
    { statename: 'Punjab'},
    { statename: 'Rajasthan'},
    { statename: 'Gujarat'},
    { statename: 'Sikkim'},
    { statename: 'Tamil Nadu'},
    { statename: 'Telangana'},
   
    { statename: 'Tripura'},
    { statename: 'Uttar Pradesh'},
    { statename: 'Uttarakhand'},
    { statename: 'West Bengal'},
   
   
 
]